[package]
name = "common"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true

[dependencies]
mpc-core = { version = "0.9.0", path = "../../mpc-core" }
mpc-net = { version = "0.4.0", path = "../../mpc-net" }
co-builder = { version = "0.4.0", path = "../co-builder" }
rayon.workspace = true
ark-serialize.workspace = true
ark-poly.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-bn254.workspace = true
eyre.workspace = true
num-bigint.workspace = true
sha3.workspace = true
itertools.workspace = true
num-traits.workspace = true
rand.workspace = true
serde.workspace = true
