inputs = ["0", "12", "3", "15"]
iv = [
    "4",
    "6",
    "12",
    "54",
    "67",
    "1",
    "45",
    "54",
    "45",
    "74",
    "0",
    "1",
    "1",
    "5",
    "6",
    "9",
]
key = [
    "1",
    "213",
    "1",
    "44",
    "45",
    "22",
    "111",
    "7",
    "12",
    "1",
    "121",
    "5",
    "7",
    "77",
    "77",
    "1",
]
