[package]
name = "poseidon_assert"
type = "bin"
authors = [""]
compiler_version = ">=0.39.0"


[dependencies]
poseidon = { tag = "v0.3.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon" }
