[network]
my_id = 1
bind_addr = "0.0.0.0:10001"
max_frame_length = 469_762_056

[[network.parties]]
id = 0
# normally we would use DNS name here such as localhost, but localhost under windows is resolved to ::1, which causes problems since we bind to ipv4 above
dns_name = "127.0.0.1:10000"

[[network.parties]]
id = 1
dns_name = "127.0.0.1:10001"

[[network.parties]]
id = 2
dns_name = "127.0.0.1:10002"

[network.tls]
key = "../data/key1.der"
certs = ["../data/cert0.der", "../data/cert1.der", "../data/cert2.der"]
