id = 1
bind_addr = "0.0.0.0:10001"
# normally we would use DNS name here such as localhost, but localhost under windows is resolved to ::1, which causes problems since we bind to ipv4 above
party_addrs = ["127.0.0.1:10000", "127.0.0.1:10001", "127.0.0.1:10002"]
party_certs = ["../data/cert0.der", "../data/cert1.der", "../data/cert2.der"]
key = "../data/key1.der"

[compiler]
allow_leaky_loops = false
link_library = ["../lib"]

[vm]
allow_leaky_logs = false
