input = [
    "1",
    "3",
    "4",
    "5",
    "6",
    "8",
    "11",
    "13",
    "14",
    "11",
    "12",
    "19",
    "21",
    "1",
    "11",
    "100",
]
state = ["1", "2", "4", "5", "7", "9", "1", "1"]
