negative = "true"
truncated = [
    "18",
    "37",
    "91",
    "204",
    "89",
    "134",
    "250",
    "3",
    "171",
    "29",
    "76",
    "48",
    "155",
    "202",
    "44",
    "67",
    "211",
    "88",
    "99",
    "120",
    "7",
    "25",
    "190",
    "142",
    "58",
    "239",
    "11",
    "65",
    "178",
    "200",
    "14",
    "77",
]
