[package]
name = "poseidon2"
type = "bin"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
poseidon2 = { tag = "v0.2.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
