[package]
name = "oblivious_map"
type = "lib"
authors = ["TACEO"]
compiler_version = ">=1.0.0"

[dependencies]
poseidon2 = { tag = "v0.3.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
