[package]
name = "collaborative-circom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
color-eyre.workspace = true
thiserror.workspace = true
serde.workspace = true
toml = "0.8.13"
circom-types = { version = "0.1.0", path = "../circom-types" }
ark-bn254.workspace = true
collaborative-groth16 = { version = "0.1.0", path = "../collaborative-groth16" }
mpc-core = { version = "0.1.0", path = "../mpc-core" }
mpc-net.workspace = true
bincode.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
rand.workspace = true
