my_id = 0
bind_addr = "0.0.0.0:10000"

[[parties]]
id = 0
dns_name = "127.0.0.1:10000"

[[parties]]
id = 1
dns_name = "127.0.0.1:10001"

[[parties]]
id = 2
dns_name = "127.0.0.1:10002"

[tls]
key = "data/key0.der"
certs = ["data/cert0.der", "data/cert1.der", "data/cert2.der"]
