name: "Audit Dependencies"
on:
  push:
    paths:
      # Run if workflow changes
      - ".github/workflows/audit.yml"
      # Run on changed dependencies
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      # Run if the configuration file changes
      - "**/audit.toml"
  # Rerun periodicly to pick up new advisories
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # v1
        with:
          toolchain: stable
      - uses: taiki-e/install-action@e407f7bafb71fd004bc5c2da3032e5470cbb6ef0 # v2.87.24
        with:
          tool: cargo-deny
      - name: Run cargo-deny
        run: cargo deny --log-level warn --all-features check ${{ matrix.checks }}
