name: "Audit Dependencies"
on:
  push:
    paths:
      # Run if workflow changes
      - ".github/workflows/audit.yml"
      # Run on changed dependencies
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      # Run if the configuration file changes
      - "**/audit.toml"
  # Rerun periodicly to pick up new advisories
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
      - uses: taiki-e/install-action@6389de18ba1f566a1d477be1660e48710dfa416f # cargo-deny
      - name: Run cargo-deny
        run: cargo deny --log-level warn --all-features check ${{ matrix.checks }}
