on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: [arc-runner-set]
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}  
