name: Rust Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL
  RUSTFLAGS: "-C link-arg=-fuse-ld=lld"

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
      - run: sudo apt-get install lld
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
      - name: Test with default features
        run: cargo test --workspace --profile ci-dev --all-features
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-groth16-examples:
    name: Test groth16 examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
      - run: sudo apt-get install lld
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
      - name: Test groth16 examples
        run: cd co-circom/co-circom/examples/groth16 && ./run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-plonk-examples:
    name: Test plonk examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
      - run: sudo apt-get install lld
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
      - name: Test plonk examples
        run: cd co-circom/co-circom/examples/plonk && ./run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-noir-examples:
    name: Test noir examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
      - run: sudo apt-get install lld
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
      - name: Test noir examples
        run: cd co-noir/co-noir/examples && ./run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
